/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account */
        post: operations["AccountsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/shipments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List shipments for an account */
        get: operations["ShipmentsController_findByAccountId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user and issue tokens */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and issue tokens */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get profile data */
        get: operations["AuthController_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/sync/shipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue shipment sync for an account */
        post: operations["SyncController_sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}/sync/tracking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue tracking sync for an account */
        post: operations["SyncController_syncTracking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["HealthController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateAccountDto: {
            /** @example Main Account */
            name: string;
            /** @example http://localhost:3000/mock/login */
            baseUrl?: string;
            /** @example gofrete-user */
            username: string;
            /** @example secret */
            password: string;
        };
        ShipmentResponseDto: {
            /** @example 8c7d2c64-9b16-4f2f-9c7a-3b1f7c7b0b6a */
            id: string;
            /** @example 4f2c1d88-4c5f-4e6d-9f5c-1f0b6b7f8b9a */
            accountId: string;
            /** @example EXT-12345 */
            externalId: string;
            /** @example finished */
            status: string;
            /** @example INV-98765 */
            invoiceCode?: Record<string, never>;
            /** @example Sao Paulo */
            origin: string;
            /** @example Rio de Janeiro */
            destination: string;
            /** @example 1200.5 */
            value: number;
            /** @example 2024-06-01T12:34:56.000Z */
            startedAt?: Record<string, never>;
            /** @example 15/06/2024 */
            deliveryEstimate: string;
            /** @example Correios */
            carrier?: Record<string, never>;
            /** @example Objeto em transporte */
            carrierStatus?: Record<string, never>;
            /** @example Saiu para entrega ao destinatario */
            statusDescription?: Record<string, never>;
            /** @example 2024-06-14T09:22:00.000Z */
            lastNotifiedAt?: Record<string, never>;
            /** @example 2024-06-15T00:00:00.000Z */
            deliveryEstimateDate?: Record<string, never>;
            /**
             * Format: date-time
             * @example 2024-06-01T12:34:56.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2024-06-02T08:22:10.000Z
             */
            updatedAt: string;
        };
        AccountResponseDto: {
            /** @example 8c7d2c64-9b16-4f2f-9c7a-3b1f7c7b0b6a */
            id: string;
            /** @example Main Account */
            name: string;
            /** @example http://localhost:3000/mock/login */
            baseUrl: string;
            /** @example gofrete-user */
            username: string;
            shipments?: components["schemas"]["ShipmentResponseDto"][];
            /**
             * Format: date-time
             * @example 2024-06-01T12:34:56.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2024-06-02T08:22:10.000Z
             */
            updatedAt: string;
        };
        CreateUserDto: {
            /** @example Jane Doe */
            name: string;
            /** @example jane@example.com */
            email: string;
            /** @example strongpassword */
            password: string;
        };
        UserResponseDto: {
            /** @example 8c7d2c64-9b16-4f2f-9c7a-3b1f7c7b0b6a */
            id: string;
            /** @example Jane Doe */
            name: string;
            /** @example jane@example.com */
            email: string;
            /** @example false */
            admin: boolean;
            /**
             * Format: date-time
             * @example 2024-06-01T12:34:56.000Z
             */
            createdAt: string;
        };
        AuthResponseDto: {
            user: components["schemas"]["UserResponseDto"];
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            accessToken: string;
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            refreshToken: string;
        };
        LoginDto: {
            /** @example jane@example.com */
            email: string;
            /** @example strongpassword */
            password: string;
        };
        SyncJobResponseDto: {
            /** @example 12345 */
            jobId: string | number;
        };
        HealthResponseDto: {
            /** @example true */
            ok: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AccountsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponseDto"];
                };
            };
        };
    };
    ShipmentsController_findByAccountId: {
        parameters: {
            query?: {
                page?: number;
                totalItems?: number;
                orderBy?: "ASC" | "DESC";
                externalId?: string;
                status?: string;
                carrierStatus?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentResponseDto"][];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    SyncController_sync: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobResponseDto"];
                };
            };
        };
    };
    SyncController_syncTracking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobResponseDto"];
                };
            };
        };
    };
    HealthController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
}
